### ISSUE TITLE
Lightbend: Could not find required component 'compiler-interface-src'

### ISSUE THREAD

**Issue by bukkasamudram** [bukkasamudram/wecareforsure#1]
Hi,

I am trying to download the app "Spark Streaming with Scala" through Lightbend Activator. The app id getting cloned successfully, but while building i am getting below exception with "Failed to load sbt configuration". Could you please help me to get resolve this.

**Exception:**
Loading project definition from C:\Users\venkateshReddy\TypeSafeTemplates\spark-streaming-scala\project
[info] Compiling 1 Scala source to C:\Users\venkateshReddy\TypeSafeTemplates\spark-streaming-scala\project\target\scala-2.10\sbt-0.13\classes...
Compiling 1 Scala source to C:\Users\venkateshReddy\TypeSafeTemplates\spark-streaming-scala\project\target\scala-2.10\sbt-0.13\classes...
Could not find required component 'compiler-interface-src'
sbt.InvalidComponent: Could not find required component 'compiler-interface-src'
    at sbt.ComponentManager.invalid(ComponentManager.scala:57)
    at sbt.ComponentManager.sbt$ComponentManager$$notFound$1(ComponentManager.scala:34)
    at sbt.ComponentManager.sbt$ComponentManager$$createAndCache$1(ComponentManager.scala:37)
    at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:27)
    at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:26)
    at sbt.ComponentManager$$anon$1.call(ComponentManager.scala:50)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:45)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)

Thanks in advance
Venky

**Comment by bukkasamudram** [comment]
Can I have some solution over here please?

**Comment by bukkasamudram** [comment]
Hi @typesafehub

May i have some update here.
